
{% set name = 'morphsnakes' %}
{% set version = '2.0.1' %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_url: ../

requirements:
  build:
    - python
    - numpy>=1.11.3
    - scipy>=0.17.0
  run:
    - python
    - numpy>=1.11.3
    - scipy>=0.17.0

build:
  noarch: python
  number: 0
  script:
    - pip install .

test:
  imports:
    - morphsnakes

app:
  summary: "The Morphological Snakes are a family of methods for image-guided
    evolution of curves and surfaces represented as a level-set of an embedding
    function. They have application in several Computer Vision areas,
    such as image segmentation and tracking."

about:
  home: https://github.com/pmneila/morphsnakes
  license: BSD-3
  license_file: LICENSE
